2024-09-09 15:43:07,672 | root | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\PythonProjects\urban_university_my_studies\_12_supporting_the_development_cycle\_04_tests.py", line 27, in test_run
    oleg = rt_with_exceptions.Runner({'Oleg'}, 5)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\urban_university_my_studies\_12_supporting_the_development_cycle\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано set
2024-09-09 15:43:07,673 | root | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\PythonProjects\urban_university_my_studies\_12_supporting_the_development_cycle\_04_tests.py", line 16, in test_walk
    alex = rt_with_exceptions.Runner('Alex', -5)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\urban_university_my_studies\_12_supporting_the_development_cycle\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
